### ISSUE TITLE
Cannot find module async/setImmediate

### ISSUE THREAD

**Issue by drauschenbach** [ipfs/js-ipfs-api#487]
I installed 12.1.0, and got this error. Call stack:

```
Error: Cannot find module 'async/setImmediate'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (.../node_modules/ipfs-block/src/index.js:4
```

**Comment by drauschenbach** [comment]
I downgraded to 10.0.0 to resolve this. This problem exists in 11.0.0 and on.

**Comment by diasdavid** [comment]
which npm version are you using @drauschenbach ?

**Comment by dignifiedquire** [comment]
This is probably related to the other PR/issue @VictorBjelkholm fixed for this, I just can't remember which module it was.

**Comment by diasdavid** [comment]
ok, @drauschenbach can you try again?

**Comment by drauschenbach** [comment]
Tried again with 12.1.2, problem remains. I'm using npm v3.9.5.

**Comment by dignifiedquire** [comment]
This was fixed in https://github.com/ipfs/js-ipfs-block/pull/23 but there was no new release of ipfs-block since then. Making a patch release for ipfs-block now, which should be picked up by a fresh install of ipfs-api.

**Comment by dignifiedquire** [comment]
Published https://github.com/ipfs/js-ipfs-block/releases/tag/v0.5.4

**Comment by drauschenbach** [comment]
This issue isn't closed until the next tag & release of `ipfs-api`.

**Comment by drauschenbach** [comment]
This issue is still with me, now due to the `peer-id` module apparently:

```
      Error: Cannot find module 'async/setImmediate'
           at Function.Module._resolveFilename (module.js:440:15)
           at Function.Module._load (module.js:388:25)
           at Module.require (module.js:468:17)
           at require (internal/module.js:20:19)
           at Object.<anonymous> (/app/node_modules/libp2p-crypto-secp256k1/src/crypto/index.js:5:22)
```

```
+-- ipfs-api@12.1.7 
| +-- async@2.1.4 
| +-- ipfs-unixfs@0.1.10 
...
| +-- peer-id@0.8.2 
...
| |   +-- libp2p-crypto-secp256k1@0.1.3 
| |   | `-- secp256k1@3.2.5 
...
```

**Comment by diasdavid** [comment]
Just released:

```
+ libp2p-crypto-secp256k1@0.1.4
[17:27:57] Published to npm.
```

Could you please try again? Apologies for the troubles, somehow this escaped CI and our testing.

**Comment by drauschenbach** [comment]
Works -- thanks!
